//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.24 at 10:09:46 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package app.core.person;
